const cafes=['Moon Brew Café','Starlight Coffee House','The Gemstone Grind','Lunar Latte Bar'];
const workshops=['Crystal Wire-Wrapping','Moonstone Bracelet Bar','Gem Carving Studio','Beaded Treasure Workshop','Celestial Keychain Lab','Sparkle & String Studio'];
const restaurants=['The Moonstone Bistro','Lunar Kitchen','Celestial Café & Grill','Gemstone Garden Restaurant'];
const pick=(items,count)=>[...items].sort(()=>Math.random()-.5).slice(0,count);
const setup=document.querySelector('#setup'),wrap=document.querySelector('#passportWrap'),nameInput=document.querySelector('#nameInput'),photoInput=document.querySelector('#photoInput'),portrait=document.querySelector('#portrait'),routeList=document.querySelector('#routeList'),qrDialog=document.querySelector('#qrDialog'),modalStop=document.querySelector('#modalStop'),checkToken=document.querySelector('#checkToken'),stampCount=document.querySelector('#stampCount'),reward=document.querySelector('#reward'),rewardTitle=document.querySelector('#rewardTitle');
let activeStamp=null;
function createRoute(){const cafe=pick(cafes,1)[0],chosenWorkshops=pick(workshops,2),restaurant=pick(restaurants,1)[0];routeList.innerHTML=`<b>1. Café:</b> ${cafe}<br><b>2. Workshop:</b> ${chosenWorkshops[0]}<br><b>3. Restaurant:</b> ${restaurant} (purchase required)<br><b>4. Workshop:</b> ${chosenWorkshops[1]}<br><b>5. Social:</b> Follow @moonstonelane`;document.querySelectorAll('.stamp')[0].dataset.stop=cafe;document.querySelectorAll('.stamp')[1].dataset.stop=chosenWorkshops[0];document.querySelectorAll('.stamp')[2].dataset.stop=restaurant;document.querySelectorAll('.stamp')[3].dataset.stop=chosenWorkshops[1];}
document.querySelector('#createPassport').addEventListener('click',()=>{const name=nameInput.value.trim()||'Guest Explorer';document.querySelector('#passportName').textContent=name;document.querySelector('#passportNo').textContent=`ML-${String(Math.floor(100000+Math.random()*900000))}`;createRoute();setup.classList.add('hidden');wrap.classList.remove('hidden');});
photoInput.addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{portrait.innerHTML=`<img src="${reader.result}" alt="Passport holder photo">`;document.querySelector('#uploadLabel').textContent='Photo added ✓';};reader.readAsDataURL(file);});
document.querySelectorAll('.stamp').forEach(stamp=>stamp.addEventListener('click',()=>{if(stamp.classList.contains('done'))return;activeStamp=stamp;modalStop.textContent=stamp.dataset.stop;checkToken.textContent=`ML-${Math.random().toString(36).slice(2,8).toUpperCase()}`;qrDialog.showModal();}));
document.querySelector('#closeQr').addEventListener('click',()=>qrDialog.close());
document.querySelector('#simulateScan').addEventListener('click',()=>{if(!activeStamp)return;activeStamp.classList.add('done');qrDialog.close();const total=document.querySelectorAll('.stamp.done').length;stampCount.textContent=`${total} / 5 STAMPS`;if(total===5){reward.classList.remove('locked');reward.classList.add('unlocked');rewardTitle.textContent='LUCKY DRAW UNLOCKED!';}activeStamp=null;});
document.querySelector('#resetPassport').addEventListener('click',()=>{wrap.classList.add('hidden');setup.classList.remove('hidden');document.querySelectorAll('.stamp').forEach(s=>s.classList.remove('done'));stampCount.textContent='0 / 5 STAMPS';reward.classList.add('locked');reward.classList.remove('unlocked');rewardTitle.textContent='COLLECT ALL 5 STAMPS';});
